name: Emerge iOS Upload (Size Analysis)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_16.4.app/Contents/Developer'

      - name: Set up Ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Setup gems
        run: |
          gem install bundler -v 2.4.0
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Install Emerge CLI
        run: |
          curl -L https://github.com/EmergeTools/cli/releases/latest/download/emerge-cli-macos.tar.gz | tar -xz
          sudo mv emerge /usr/local/bin/
          emerge --version

        - name: Build & upload iOS size analysis binary to Emerge Tools
          run: bundle exec fastlane ios build_upload_emerge
          env:
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
            CONFIGURATION: Release
            EMERGE_BUILD_TYPE: ${{ github.event_name == 'pull_request' && 'pull-request' || 'main' }}
            GITHUB_PR_NUMBER: ${{ github.event_name == 'pull_request' && github.event.number || '' }}
            GITHUB_BASE_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || '' }}
            SENTRY_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
