name: Emerge iOS Upload (Size Analysis)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_16.4.app/Contents/Developer'

      - name: Set up Ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Setup gems
        run: |
          gem install bundler -v 2.4.0
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Build & upload iOS size analysis binary to Emerge Tools
        run: bundle exec fastlane ios build_and_upload_to_sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          GITHUB_PR_NUMBER: ${{ github.event_name == 'pull_request' && github.event.number || '' }}
          GITHUB_BASE_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || '' }}
          SENTRY_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          FASTLANE_XCODEBUILD_SETTINGS_ALLOW_PROVISIONING_UPDATES: true
